### ISSUE TITLE
Enhance framework to proxy concrete instances

### ISSUE THREAD

**Issue by witherspore** [tacitknowledge/slow-light#1]
Currently perf-degradation only supports interfaces using the java.lang.reflect Proxy technology.  Please note that this is part of the **embedded** module

Please extend the proxy module so that it can proxy concrete classes.  See the Mockito OSS project source code for assistance on proxying concretes.  it will rely on asm or some byte code manipulation.  Lots of projects do this.

**Comment by psorocun** [comment]
The issue has been implemented using Javassist library (as cglib has been deprecated). Hence, it's possible to create dynamic proxies for concrete classes and inject degradation behaviour for services and facades.
